[package]
name = "snowdrop_dirs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
miette = "5.5.0"
once_cell = "1.17.0"
